<div id="Data" style="display: none;">
    {{--攻防能力--}}
    @component('pc.match_detail.foot_cell.data_attribute',['match'=>$match,'analyse'=>$analyse])
    @endcomponent
    {{--盘口,另外数据刷新--}}
    @component('pc.match_detail.foot_cell.data_odd',['mid'=>$match['mid']])
    @endcomponent
    {{--联赛排名--}}
    @component('pc.match_detail.foot_cell.data_league',['match'=>$match,'analyse'=>$analyse])
    @endcomponent
    {{--交锋--}}
    @if(isset($analyse['historyBattle'])&&isset($analyse['historyBattle']['historyBattle']))
        @component('pc.match_detail.foot_cell.data_battle',['match'=>$match,'historyBattle'=>$analyse['historyBattle']['historyBattle']])
        @endcomponent
    @endif
    @if(isset($analyse['recentBattle']))
        {{--近期战绩--}}
        @component('pc.match_detail.foot_cell.data_history',['match'=>$match,'analyse'=>$analyse,'recentBattle'=>$analyse['recentBattle']])
        @endcomponent
    @endif
    {{--赛事盘路--}}
    @component('pc.match_detail.foot_cell.data_trend',['match'=>$match,'analyse'=>$analyse])
    @endcomponent
    @if(isset($analyse['schedule']))
        {{--未来赛程--}}
        @component('pc.match_detail.foot_cell.data_schedule',['currmatch'=>$match,'analyse'=>$analyse])
        @endcomponent
    @endif
</div>