<div class="first">
    <p class="title">比赛阵容</p>
    <div class="part host">
        <p class="name">休斯顿迪纳摩</p>
        <table>
            <thead>
            <tr>
                <th>首发</th>
                <th>后备</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><p>1</p>威利斯</td>
                <td><p>1</p>威利斯</td>
            </tr>
            <tr>
                <td><p>1</p>比斯利</td>
                <td><p>1</p>比斯利</td>
            </tr>
            <tr>
                <td><p>1</p>森德罗斯</td>
                <td><p>1</p>森德罗斯</td>
            </tr>
            <tr>
                <td><p>1</p>艾度科玛查度</td>
                <td><p>1</p>艾度科玛查度</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>威利斯</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>比斯利</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>森德罗斯</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>艾度科玛查度</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>威利斯</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>比斯利</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>森德罗斯</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="part away">
        <p class="name">休斯顿迪纳摩</p>
        <table>
            <thead>
            <tr>
                <th>首发</th>
                <th>后备</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><p>1</p>威利斯</td>
                <td><p>1</p>威利斯</td>
            </tr>
            <tr>
                <td><p>1</p>比斯利</td>
                <td><p>1</p>比斯利</td>
            </tr>
            <tr>
                <td><p>1</p>森德罗斯</td>
                <td><p>1</p>森德罗斯</td>
            </tr>
            <tr>
                <td><p>1</p>艾度科玛查度</td>
                <td><p>1</p>艾度科玛查度</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>威利斯</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>比斯利</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>森德罗斯</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>艾度科玛查度</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>威利斯</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>比斯利</td>
            </tr>
            <tr>
                <td></td>
                <td><p>1</p>森德罗斯</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>