<?php
/**
 * Created by PhpStorm.
 * User=> maozhijun
 * Date=> 17/1/16
 * Time=> 12=>53
 */

namespace App\Http\Controllers\App\MatchDetail\Football;


trait WhoscoredAliases
{
    //别名
    public $kAliasesCN = [
        "Spartak Moscow" => "莫斯科斯巴达",
        "Ural" => "乌拉尔",
        "Terek Grozny" => "格罗兹尼特里克",
        "FC Rostov" => "罗斯托夫",
        "Lokomotiv Moscow" => "莫斯科火车头",
        "CSKA Moscow" => "莫斯科中央陆军",
        "Zenit St. Petersburg" => "圣彼得堡泽尼特",
        "Anzhi Makhachkala" => "安郅马哈奇卡拉",
        "FC Orenburg" => "奥伦堡加索维克",
        "Krylya Sovetov Samara" => "苏维埃之翼",
        "FC Ufa" => "乌法",
        "Arsenal Tula" => "图拉兵工厂",
        "Amkar" => "阿姆卡尔",
        "FC Krasnodar" => "克拉斯诺达尔",
        "Rubin Kazan" => "喀山鲁宾",
        "Tom Tomsk" => "托木斯克",

        "New York City FC" => "纽约城",
        "New York Red Bulls" => "纽约红牛",
        "Montreal Impact" => "蒙特利尔冲击",
        "Toronto FC" => "多伦多FC",
        "Philadelphia Union" => "费城联合",
        "Orlando City" => "奥兰多城",
        "New England Rev." => "新英格兰革命",
        "DC United" => "华盛顿联",
        "Columbus Crew" => "哥伦布机员",
        "Chicago Fire" => "芝加哥火焰",
        "FC Dallas" => "达拉斯FC",
        "Colorado Rapids" => "科罗拉多急流",
        "LA Galaxy" => "洛杉矶银河",
        "Sporting Kansas City" => "肯萨斯竞技",
        "Real Salt Lake" => "皇家盐湖城",
        "Vancouver Whitecaps" => "温哥华白帽",
        "Portland Timbers" => "波特兰伐木者",
        "San Jose Earthquakes" => "圣何塞地震",
        "Seattle Sounders FC" => "西雅图音速",
        "Houston Dynamo" => "休斯敦迪纳摩",

        "Corinthians" => "科林蒂安",
        "Santos FC" => "桑托斯",
        "Palmeiras" => "帕尔梅拉斯",
        "Gremio" => "格雷米奥",
        "Flamengo" => "弗拉门戈",
        "Atletico MG" => "米内罗竞技",
        "Atletico PR" => "巴拉纳竞技",
        "Ponte Preta" => "庞特普雷塔",
        "Fluminense" => "弗鲁米嫩塞",
        "Sao Paulo" => "圣保罗",
        "Chapecoense AF" => "沙佩科恩斯",
        "Sport" => "累西腓体育",
        "Internacional" => "巴西国际",
        "Botafogo RJ" => "博塔弗戈",
        "Figueirense" => "费古埃伦斯",
        "Vitoria" => "维多利亚",
        "Coritiba" => "科里蒂巴",
        "Santa Cruz" => "圣十字",
        "Cruzeiro" => "克鲁塞罗",
        "America MG" => "米涅美洲",

        "Guangzhou Evergrande" => "广州恒大淘宝",
        "Jiangsu Suning FC" => "江苏苏宁",
        "Shanghai SIPG FC" => "上海上港",
        "Shanghai Shenhua" => "上海绿地申花",
        "Hebei CFFC" => "河北华夏幸福",
        "Guangzhou R&F F.C." => "广州富力",
        "Yanbian" => "延边富德",
        "Henan Jianye" => "河南建业",
        "Beijing Guoan" => "北京国安乐视",
        "Liaoning Hongyun" => "辽宁沈阳宏运",
        "Chongqing Lifan" => "重庆力帆",
        "Tianjin Teda" => "天津泰达亿利",
        "Hangzhou Greentown" => "杭州绿城",
        "Shandong Luneng" => "山东鲁能泰山",
        "Shijiazhuang Ever Bright" => "石家庄永昌",
        "Changchun Yatai" => "长春亚泰",

        "Rosenborg" => "罗森博格",
        "Odds Ballklubb" => "奥德格伦兰",
        "Brann" => "布兰",
        "Stroemsgodset" => "斯托姆加斯特",
        "Sarpsborg 08" => "萨普斯堡",
        "FK Haugesund" => "海于格松",
        "Viking" => "维京",
        "Sogndal" => "松达尔",
        "Molde" => "莫尔德",
        "Tromsoe" => "特罗姆瑟",
        "Lillestroem" => "利勒斯特罗姆",
        "Bodoe/Glimt" => "博多格林特",
        "Vaalerenga" => "瓦勒伦加",
        "Stabaek" => "斯塔贝克",
        "Aalesund" => "奥勒松",
        "Start" => "斯达",

        "ADO Den Haag" => "海牙",
        "Ajax" => "阿贾克斯",
        "AZ Alkmaar" => "艾克马亚",
        "Excelsior" => "SBV精英",
        "FC Groningen" => "格罗宁根",
        "FC Utrecht" => "乌德勒支",
        "Feyenoord" => "费耶诺德",
        "Go Ahead Eagles" => "前进之鹰",
        "Heracles" => "赫拉克莱斯",
        "NEC Nijmegen" => "尼美根",
        "PEC Zwolle" => "泽沃勒",
        "PSV Eindhoven" => "埃因霍温",
        "Roda" => "罗达JC",
        "SC Heerenveen" => "海伦芬",
        "Sparta Rotterdam" => "鹿特丹斯巴达",
        "Twente" => "特温特",
        "Vitesse" => "维迪斯",
        "Willem II" => "威廉二世",

        "Aston Villa" => "阿斯顿维拉",
        "Barnsley" => "巴恩斯利",
        "Birmingham" => "伯明翰",
        "Blackburn" => "布莱克本",
        "Brentford" => "布伦特福德",
        "Brighton" => "布莱顿",
        "Bristol City" => "布里斯托城",
        "Burton" => "伯顿",
        "Cardiff" => "卡迪夫城",
        "Derby" => "德比郡",
        "Fulham" => "富勒姆",
        "Huddersfield" => "哈德斯菲尔德",
        "Ipswich" => "伊普斯维奇",
        "Leeds" => "利兹联",
        "Newcastle United" => "纽卡斯尔联",
        "Norwich" => "诺维奇",
        "Nottingham Forest" => "诺丁汉森林",
        "Preston" => "普雷斯顿",
        "Queens Park Rangers" => "女王公园巡游者",
        "Reading" => "雷丁",
        "Rotherham" => "罗瑟汉姆",
        "Sheffield Wednesday" => "谢周三",
        "Wigan" => "维冈竞技",
        "Wolverhampton Wanderers" => "狼队",

        "Manchester City" => "曼城",
        "Manchester United" => "曼联",
        "Hull" => "赫尔城",
        "Chelsea" => "切尔西",
        "Middlesbrough" => "米德尔斯堡",
        "Everton" => "埃弗顿",
        "Tottenham" => "热刺",
        "Burnley" => "伯恩利",
        "West Bromwich Albion" => "西布罗姆维奇",
        "West Ham" => "西汉姆",
        "Liverpool" => "利物浦",
        "Swansea" => "斯旺西",
        "Arsenal" => "阿森纳",
        "Watford" => "沃特福德",
        "Leicester" => "莱切斯特城",
        "Southampton" => "南安普敦",
        "Stoke" => "斯托克城",
        "Sunderland" => "桑德兰",
        "Crystal Palace" => "水晶宫",
        "Bournemouth" => "伯恩茅斯",

        "Roma" => "罗马",
        "Genoa" => "热那亚",
        "Chievo" => "切沃",
        "Lazio" => "拉齐奥",
        "AC Milan" => "AC米兰",
        "Juventus" => "尤文图斯",
        "Sampdoria" => "桑普多利亚",
        "Bologna" => "博洛尼亚",
        "Sassuolo" => "森索罗",
        "Napoli" => "那不勒斯",
        "Pescara" => "佩斯卡拉",
        "Atalanta" => "亚特兰大",
        "Torino" => "都灵",
        "Fiorentina" => "佛罗伦萨",
        "Crotone" => "克罗托内",
        "Palermo" => "巴勒莫",
        "Empoli" => "恩波利",
        "Cagliari" => "卡利亚里",
        "Inter" => "国际米兰",
        "Udinese" => "乌迪内斯",

        "Barcelona" => "巴塞罗那",
        "Real Madrid" => "皇家马德里",
        "Sevilla" => "塞维利亚",
        "Las Palmas" => "拉斯帕尔马斯",
        "Deportivo La Coruna" => "拉科鲁尼亚",
        "Sporting Gijon" => "希洪竞技",
        "Leganes" => "雷加利斯",
        "Alaves" => "阿拉维斯",
        "Osasuna" => "奥萨苏纳",
        "Villarreal" => "比利亚雷亚尔",
        "Granada" => "格拉那达",
        "Malaga" => "马拉加",
        "Atletico Madrid" => "马德里竞技",
        "Eibar" => "埃瓦尔",
        "Athletic Club" => "毕尔巴鄂竞技",
        "Celta Vigo" => "塞尔塔",
        "Espanyol" => "西班牙人",
        "Valencia" => "巴伦西亚",
        "Real Sociedad" => "皇家社会",
        "Real Betis" => "皇家贝蒂斯",

        "Augsburg" => "奥格斯堡",
        "Bayer Leverkusen" => "勒沃库森",
        "Bayern Munich" => "拜仁慕尼黑",
        "Borussia Dortmund" => "多特蒙德",
        "Borussia M.Gladbach" => "门兴格拉德巴赫",
        "Darmstadt" => "达姆斯塔特",
        "Eintracht Frankfurt" => "法兰克福",
        "FC Cologne" => "科隆",
        "Freiburg" => "弗赖堡",
        "Hamburger SV" => "汉堡",
        "Hertha Berlin" => "柏林赫塔",
        "Hoffenheim" => "霍芬海姆",
        "Ingolstadt" => "英格斯塔",
        "Mainz 05" => "美因茨",
        "RasenBallsport Leipzig" => "RB莱比锡",
        "Schalke 04" => "沙尔克04",
        "Werder Bremen" => "云达不莱梅",
        "Wolfsburg" => "沃尔夫斯堡",

        "Lyon" => "里昂",
        "Paris Saint Germain" => "巴黎圣日尔曼",
        "Nice" => "尼斯",
        "Toulouse" => "图卢兹",
        "Guingamp" => "甘冈",
        "Monaco" => "摩纳哥",
        "SC Bastia" => "巴斯蒂亚",
        "Saint-Etienne" => "圣埃蒂安",
        "Rennes" => "雷恩",
        "Lille" => "里尔",
        "Nantes" => "南特",
        "Caen" => "卡昂",
        "Montpellier" => "蒙彼利埃",
        "Bordeaux" => "波尔多",
        "Metz" => "梅斯",
        "Marseille" => "马赛",
        "Angers" => "安格斯",
        "Dijon" => "第戎",
        "Lorient" => "洛里昂",
        "Nancy" => "南锡",

        "FC Porto" => "波尔图",
        "Sporting CP" => "里斯本竞技",
        "Moreirense" => "摩里伦斯",
        "Vitoria de Setubal" => "塞图巴尔",
        "Benfica" => "本菲卡",
        "Boavista" => "博阿维斯塔",
        "Braga" => "布拉加",
        "Vitoria de Guimaraes" => "吉马雷斯",
        "Arouca" => "艾路卡",
        "Feirense" => "费伦斯",
        "Chaves" => "查维斯",
        "Pacos de Ferreira" => "费雷拉",
        "Rio Ave" => "里奥阿维",
        "Tondela" => "唐迪拉",
        "Belenenses" => "比兰尼塞斯",
        "Nacional" => "葡萄牙国民",
        "Estoril" => "埃斯托里尔",
        "Maritimo" => "马里迪莫",

        "Besiktas" => "贝西克塔斯",
        "Genclerbirligi" => "根克勒比利吉",
        "Trabzonspor" => "特拉布宗体育",
        "Akhisar Belediyespor" => "阿卡沙",
        "Bursaspor" => "布尔萨体育",
        "Galatasaray" => "加拉塔萨雷",
        "Istanbul Basaksehir" => "伊斯坦堡普野社希尔",
        "Konyaspor" => "科尼亚体育",
        "Rizespor" => "里泽斯堡",
        "Osmanlispor FK" => "奥斯曼里士邦",
        "Antalyaspor" => "安塔利亚体育",
        "Adanaspor" => "艾丹亚斯普",
        "Fenerbahce" => "费内巴切",
        "Karabukspor" => "卡拉比克体育",
        "Kasimpasa" => "卡斯帕萨",
        "Kayserispor" => "开塞利体育",
        "Gaziantepspor" => "加济安泰普体育",
        "Alanyaspor" => "阿兰亚斯堡",

        "Malmoe FF" => "马尔默",
        "AIK" => "索尔纳",
        "IFK Norrkoeping" => "诺科平",
        "IFK Gothenburg" => "哥德堡",
        "Oerebro" => "奥雷布洛",
        "Elfsborg" => "埃尔夫斯堡",
        "Kalmar FF" => "卡尔马",
        "Hammarby" => "哈马比",
        "Haecken" => "赫根",
        "Djurgaarden" => "佐加顿斯",
        "Oestersunds FK" => "奥斯特桑斯",
        "Joenkoepings Soedra" => "佐高平斯",
        "GIF Sundsvall" => "松兹瓦尔",
        "Helsingborg" => "赫尔辛堡",
        "Gefle" => "耶夫勒",
        "Falkenbergs FF" => "法尔肯堡",

        "Estudiantes" => "拉普拉塔大学生",
        "San Lorenzo" => "圣洛伦索",
        "Newells Old Boys" => "纽维尔老男孩",
        "Boca Juniors" => "博卡青年",
        "River Plate" => "河床",
        "Racing Club" => "竞技俱乐部",
        "Colon" => "科隆竞技",
        "Independiente" => "阿根廷独立",
        "Atletico Rafaela" => "拉斐拉竞技",
        "Lanus" => "拉努斯",
        "Atletico Tucuman" => "图库曼竞技",
        "Rosario Central" => "罗萨里奥中央",
        "Gimnasia LP" => "拉普拉塔体操",
        "Banfield" => "班菲尔德",
        "Union" => "圣塔菲联",
        "Temperley" => "CA坦波利",
        "Godoy Cruz" => "戈多伊克鲁斯",
        "Huracan" => "飓风队",
        "Tigre" => "泰格雷",
        "Defensa y Justicia" => "防卫者",
        "Belgrano" => "贝尔格拉诺",
        "Quilmes" => "基尔梅斯",
        "Aldosivi" => "阿尔多斯维",
        "Velez Sarsfield" => "萨斯菲尔德",
        "Talleres" => "塔勒瑞斯",
        "Olimpo" => "奥林匹奥",
        "Sarmiento" => "萨尔米安杜",
        "Patronato de Parana" => "帕特罗纳图",
        "San Martin San Juan" => "圣胡安圣马丁",
        "Arsenal Sarandi" => "萨兰迪兵工厂",


        "England" => "英格兰",
        "Italy" => "意大利",
        "Spain" => "西班牙",
        "Germany" => "德国",
        "France" => "法国",
        "Portugal" => "葡萄牙",
        "Netherlands" => "荷兰",
        "Russia" => "俄罗斯",
        "Brazil" => "巴西",
        "USA" => "美国",
        "Turkey" => "土耳其",
        "Argentina" => "阿根廷",
        "China" => "中国",
        "Norway" => "挪威",
        "Sweden" => "瑞典",

        "England-Premier League" => "英超",
        "Italy-Serie A" => "意甲",
        "England-Championship" => "英冠",
        "Spain-La Liga" => "西甲",
        "Germany-Bundesliga" => "德甲",
        "Germany 2. Bundesliga"=>"德乙",
        "France-Ligue 1" => "法甲",
        "Portugal-Liga NOS" => "葡超",
        "Netherlands-Eredivisie" => "荷甲",
        "Russia-Premier League" => "俄超",
        "Brazil-Brasileirão" => "巴西甲",
        "USA-Major League Soccer" => "美职联",
        "Turkey-Super Lig" => "土超",
        "Argentina-Primera División " => "阿甲",
        "China-Super league" => "中超",
        "Norway-Tippeligaen" => "挪超",
        "Sweden-Allsvenskan" => "瑞典超"
    ];

    //球队特点
    public $kCharacteristicsCN = [
        "Attacking down the wings" => "边路进攻(两翼)",
        "Attacking set pieces" => "定位球进攻",
        "Creating offside" => "造越位",
        "Creating chances through individual skill" => "个人能力创造机会",
        "Creating chances using through balls" => "使用直塞球创造机会",
        "Creating long shot opportunities" => "创造远射时机",
        "Creating scoring chances" => "创造得分机会",
        "Coming back from losing positions" => "失位回补",
        "Counter attacks" => "反击",
        "Finishing scoring chances" => "把握得分机会",
        "Keeping possession of the ball" => "控球(能力)",
        "Shooting from direct free kicks" => "直接任意球射门",
        "Aerial duels" => "争高空球",
        "Avoiding fouling in dangerous areas" => "避免在禁区犯规",
        "Avoiding individual errors" => "避免个人失误",
        "Avoiding offside" => "避免越位(能力)",
        "Defending against attacks down the wings" => "对边路(两翼)进攻的防守",
        "Defending against long shots" => "远射防守(能力)",
        "Defending against skillful players" => "对个人能力出众球员的防守",
        "Defending against through ball attacks" => "对直塞球的防御(能力)",
        "Defending counter attacks" => "防守反击",
        "Defending set pieces" => "区域防守(能力)",
        "Protecting the lead" => "保护领先优势",
        "Stopping opponents from creating chances" => "阻止对手创造机会",
        "Stealing the ball from the opposition" => "从对方脚下断球"
    ];

    //球队风格
    public $kStyleCN = [
        "Attempt crosses often" => "经常尝试大范围转移",
        "Attacking down the left" => "左边路进攻(下底)",
        "Attacking down the right" => "右边路进攻(下底)",
        "Attempt through balls often" => "经常尝试直塞球",
        "Attack through the middle" => "中路渗透进攻",
        "Control the game in the opposition's half" => "将球控制在对方半场",
        "Long balls" => "长传球",
        "Play with width" => "利用球场宽度",
        "Possession football" => "控球",
        "Short passes" => "短传",
        "Take a lot of shots" => "获得大量的射门",
        "Take long shots" => "采取远射",
        "Aggressive" => "积极",
        "Consistent first eleven" => "一贯的首发11人",
        "Non-aggressive" => "非侵略性(动作不大)",
        "Opponents play aggressively against them" => "对抗激烈",
        "Play the offside trap" => "造越位",
        "Playing in their own half" => "在本方半场控制比赛",
        "Rotate their first eleven" => "轮换的首发11人"
    ];

    //比赛预测
    public $kForecastCN = [
        "will make a comeback if they go behind" => "如果落后有可能反超",
        "will score as a result of individual skill" => "利用个人能力进球得分",
        "will score from a direct freekick" => "任意球直接得分",
        "Attempt through balls often" => "",
        "There will be a high number of cards shown" => "比赛会有更多的红黄牌",
        "will dominate in the air" => "取得制空权",
        "will score a long shot" => "利用远射得分",
        "will control the game in the opposition's half" => "将球控制在对方半场",
        "will score from a fast break situation" => "快速进攻的情况下得分",
        "will create many scoring chances" => "将创造很多得分机会",
        "will dominate possession" => "将占据优势",
        "will score as a result of an opposition error" => "将对手的失误转化为进球",
        "will score as a result of a through ball" => "将通过直塞球(威胁球)得分",
        "will score from a wingplay situation" => "结果取决于边路的表现",
        "will be shown a high number of cards" => "会被出示很多红黄牌",
        "will stray offside often" => "会经常陷入越位",
        "will steal the ball from the opposition often" => "经常从对方脚下断球",
        "will score from a setpiece situation" => "通过定位球得分",
        "steal the ball from the opposition often" => "经常从对方脚下断球",
        "There will be a low number of cards shown" => "比赛红黄牌比较少",
    ];

    //形容词
    public $kAdjCN = [
        "Very Strong" => [
            "cn" => "很强",
            "style" => "limegreen"
        ],
        "Extremely Strong" => [
            "cn" => "非常强",
            "style" => "darkgreen"
        ],
        "Strong" => [
            "cn" => "强",
            "style" => "lightseagreen"
        ],
        "Weak" => [
            "cn" => "弱",
            "style" => "orange"
        ],
        "Very Weak" => [
            "cn" => "很弱",
            "style" => "indianred"
        ],
        "Extremely Weak" => [
            "cn" => "非常弱",
            "style" => "darkred"
        ],
        "Likely" => [
            "cn" => "可能",
            "style" => "orange"
        ],
        "Very Likely" => [
            "cn" => "很有可能",
            "style" => "limegreen"
        ],
        "Extremely Likely" => [
            "cn" => "非常可能",
            "style" => "darkgreen"
        ],
        "Defensive" => [
            "cn" => "防守",
            "style" => "attrDefensive"
        ],
        "Offensive" => [
            "cn" => "进攻",
            "style" => "attrOffensive"
        ]
    ];
}