<tr>
    <td>{{$name}}</td>
    <td>{{$odd['asiaWin']}}/{{$odd['asiaDraw']}}/{{$odd['asiaLose']}}</td>
    <td>{{$odd['asiaPercent']}}%</td>
    <td>{{$odd['goalBig']}}</td>
    <td>{{$odd['goalBigPercent']}}%</td>
    <td>{{$odd['goalSmall']}}</td>
    <td>{{$odd['goalSmallPercent']}}%</td>
</tr>
