<table ha="{{$ha}}" le="{{$le}}">
    <thead>
        <tr>
            <th>球队</th>
            <th>场均进球</th>
            <th>场均失球</th>
            <th>进球场次</th>
            <th>失球场次</th>
        </tr>
    </thead>
    <tbody>
            <tr>
                <td>{{$match['hname']}}</td>
                @if(isset($home))
                    <td>{{$home['avgGoal']}}球</td>
                    <td>{{$home['avgMiss']}}球</td>
                    <td>{{$home['avgGoalMatch']}}场</td>
                    <td>{{$home['avgMissMatch']}}场</td>
                @else
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                @endif
            </tr>
            <tr>
                <td>{{$match['aname']}}</td>
                @if(isset($away))
                    <td>{{$away['avgGoal']}}球</td>
                    <td>{{$away['avgMiss']}}球</td>
                    <td>{{$away['avgGoalMatch']}}场</td>
                    <td>{{$away['avgMissMatch']}}场</td>
                @else
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                @endif
            </tr>
            <tr>
                <td colspan="5">* 近10场，如不够10场则以球队显示场数为准</td>
            </tr>
    </tbody>
</table>